### ISSUE TITLE
Feat: Dependency Graph

### ISSUE THREAD

**Issue by stropho** [bschaepper/yaioc#3]
Great to see that this project is active :)

I love the idea about the Dependency Graph. I would also like to have diagram for all the dependencies. I understand that
1. it could be difficult to visualize it in the terminal
2. it is not appropriate to include any library rendering some graphical chart in this package

# Goal
After a little research, it seems that the easiest way to generate some kind of relation diagram would be to use a dot file ( https://en.wikipedia.org/wiki/DOT_(graph_description_language) ) There are plenty of tools that can generate output based on the dot file. I don't think it is even necessary to generate the dot file itself by this package.

# Output
A simple structure as output would be sufficient to generate a dot file. Or to do any other analysis if it is the case.
For example
```js
[
  ['componentFoo', ['dep1', 'dep2'],]
  ['componentBar', ['componentFoo', 'dep2']],
  // ...
]
```

## What now ?
I'm willing to do (or help with)  the PR. It seems it might not be that straightforward because of the possible children containers. Any pointers would be appreciated.

What do you think ?

**Comment by bschaepper** [comment]
Alive and kicking, as they say ;)

> I would also like to have diagram for all the dependencies

Just to clarify, is this meant _additionally_ to all dependencies known to yaioc, meaning `require`d and `import`d dependencies?

**Comment by stropho** [comment]
> Just to clarify, is this meant _additionally_ to all dependencies known to yaioc, meaning `require`d and `import`d dependencies?

Not sure I understand the question right :) 
For example:
```js
// ...
container.registerValue('foo', require('npm-pkg'))
container.registerFactory('bar', (foo) => ({}))
container.registerFactory('baz', (foo) => ({}))
```
I would like to extract all the registered names `foo` , `bar` , and `baz` and their dependencies names. Filenames or package names like `npm-pkg` are not relevant - not sure if that would even be possible.

**Comment by bschaepper** [comment]
OK cool, then we're on the same page. I like your idea with the Dot file a lot. And it seems easy enough to generate it, all it comes down to is listing all registered components in the container and their dependencies one by one. This fully defines the graph, and the visualization should figure out the rest.

If you'd like to try and implement it, I think you can start in the `DependencyGraph` class, and reimplement a `DependencyGraphPrinter` for DOT files instead of console output. 

This project is 99% TDD, I'd suggest you do the same. I don't quite remember the data structure in `DependencyGraph`, off the top of my head, but as far as I remember it should be more or less self explanatory, if you start by looking at the corresponding tests.

And please feel free to add your name to contributors in `package.json` :)
